---
- name: Patch Vulnerable Windows Servers and Manage Security Patches
  hosts: windows_servers
  become: yes
  tasks:
    - name: Install PSWindowsUpdate module
      win_psmodule:
        name: PSWindowsUpdate
        state: present

    - name: Run Windows Update
      win_shell: |
        Install-Module PSWindowsUpdate -Force -AcceptAll
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -Install -AcceptAll -AutoReboot
      register: update_result

    - name: Reboot the server if updates were installed
      win_reboot:
        when: update_result.reboot_required

    - name: Verify the updates have been applied
      win_shell: |
        $pending = Get-WindowsUpdate -IsInstalled
        if ($pending) {exit 1}
        exit 0
      register: check_result
      ignore_errors: yes

    - name: Fail if updates are still pending
      fail:
        msg: "Security updates are still pending"
      when: check_result.rc != 0
