---
    # This Playbook file is an automation script for installing, launching, and enabling packetbeat to be integrated with an ELK instance.
    - name: Installing and Launching Packetbeat
      hosts: webservers
      become: yes
      tasks:
        # Use curl module to download latest version of packetbeat 
      - name: Download packetbeat .deb file
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-8.3.1-amd64.deb
    
        # Use dkpg module to install packetbeat
      - name: Install packetbeat .deb
        command: dpkg -i packetbeat-8.3.1-amd64.deb
    
        # Use copy module to copy and drop packetbeat yaml file from ansible into packetbeat configuration
      - name: Drop in packetbeat.yml
        copy:
          src: /etc/ansible/packetbeat-config.yml
          dest: /etc/packetbeat/packetbeat.yml
    
        # Use enable module to enable packetbeat to system
      - name: Enable and Configure System Module
        command: packetbeat modules enable system
    
        # Use setup module to setup packetbeat
      - name: Setup filebeat
        command: filebeat setup
    
        # Use start module to start packetbeat service
      - name: Start packetbeat service
        command: service packetbeat start
    
        # Use systemd module to enable packetbeat upon boot
      - name: Enable service packetbeat on boot
        systemd:
          name: packetbeat
          enabled: yes