---
# Playbook file automates ELK configuration with docker to monitor changes to system metrics and logs. 
# Note: In order to use the playbook, you need to have an ansible control node configured.
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: sysadmin
  become: true
  tasks:
    # Use apt module to install docker images
    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

      # Use apt module to install python3-pip
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

      # Use pip module to install docker python module
    - name: Install Docker python module
      pip:
        name: docker
        state: present

      # Use sysctl module to increase system memory
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

      # Use docker container module to launch elk docker container.
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

      # Use systemd module to enable docker service on boot.
    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes