---
- name: Patch Vulnerable Linux Servers and Manage Security Patches
  hosts: linux_servers
  become: yes
  tasks:
    - name: Ensure all packages are up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Apply security updates only
      apt:
        update_cache: yes
        upgrade: safe
        autoremove: yes

    - name: Reboot the server if a reboot is required
      reboot:
        when: ansible_facts.packages['unattended-upgrades'] is changed

    - name: Verify the security updates have been applied
      shell: apt list --upgradable
      register: result

    - name: Fail if security updates are still pending
      fail:
        msg: "Security updates are still pending"
      when: result.stdout != ''
